[phases.install]
cmds = [
  "npm install --legacy-peer-deps",
  "npm install --legacy-peer-deps --cpu=x64 --os=linux lightningcss-linux-x64-gnu"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "caddy run --config /assets/Caddyfile --adapter caddyfile"
