// Types matching the Supabase schema (initial + v6 enhancements).
// Replace with: npx supabase gen types typescript --project-id <ref> > src/types/database.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type TrainingMode = 'gym' | 'smith_machine' | 'lower_fatigue';
export type RecoveryRating = 'great' | 'normal' | 'poor';
export type ExperienceLevel = 'beginner' | 'intermediate' | 'experienced' | 'experienced_detrained';
export type PrimaryGoal = 'build_muscle' | 'lose_fat' | 'recomp' | 'get_stronger' | 'general_fitness';
export type SessionDuration = '30-45' | '45-60' | '60-75' | '75+';
export type TrainingLocation = 'gym' | 'home' | 'both';
export type FormExplanationLevel = 'all' | 'new_only' | 'none';
export type SplitType = 'full_body' | 'upper_lower' | 'ppl' | 'ppl_x2' | 'upper_lower_ppl';
export type ActivityLevel = 'sedentary' | 'lightly_active' | 'moderately_active' | 'very_active' | 'extremely_active';
export type MealsPerDay = '2' | '3' | '4' | '5' | '6+';
export type EatingApproach = 'no_preference' | 'clean_eating' | 'flexible_dieting' | 'keto' | 'high_carb' | 'intermittent_fasting';
export type MealType = 'breakfast' | 'lunch' | 'dinner' | 'snack';
export type FoodSource = 'usda' | 'openfoodfacts' | 'manual';
export type DayTemplate = 'upper_a' | 'lower_a' | 'upper_b' | 'lower_b' | 'push_a' | 'pull_a' | 'legs_a' | 'push_b' | 'pull_b' | 'legs_b' | 'full_a' | 'full_b' | 'full_c';
export type PreMood = 'energized' | 'normal' | 'low_energy';
export type CardioType = 'walking' | 'running' | 'cycling' | 'swimming' | 'rowing' | 'elliptical' | 'stairmaster' | 'hiit' | 'jump_rope' | 'other';
export type CardioIntensity = 'low' | 'moderate' | 'high' | 'max';
export type DistanceUnit = 'miles' | 'km' | 'meters';
export type ExerciseCategory = 'strength' | 'stretching' | 'plyometrics' | 'strongman' | 'powerlifting' | 'cardio' | 'olympic_weightlifting';
export type ExerciseSource = 'seed' | 'free_exercise_db' | 'exercisedb_api' | 'user';
export type TipCategory = 'form_cue' | 'hypertrophy_tip' | 'common_mistake' | 'muscle_activation' | 'breathing' | 'progression';
export type TooltipCategory = 'training' | 'nutrition' | 'recovery' | 'anatomy';

export interface Database {
  public: {
    Tables: {
      user_profiles: {
        Row: {
          id: string;
          display_name: string | null;
          height_inches: number | null;
          current_weight: number | null;
          target_weight: number | null;
          protein_target_min: number;
          protein_target_max: number;
          calorie_target: number;
          equipment_available: string[];
          training_mode: TrainingMode;
          sex: string | null;
          experience_level: ExperienceLevel | null;
          primary_goal: PrimaryGoal | null;
          training_days_per_week: number | null;
          preferred_days: string[] | null;
          session_duration: SessionDuration | null;
          training_location: TrainingLocation | null;
          injuries: string[] | null;
          avoided_exercises: string[] | null;
          tracks_macros: boolean;
          takes_creatine: boolean;
          detrained_duration: string | null;
          previous_training_style: string | null;
          show_tooltips: boolean;
          show_form_explanations: FormExplanationLevel;
          split_type: SplitType;
          onboarding_completed: boolean;
          onboarding_completed_at: string | null;
          compound_rep_min: number;
          compound_rep_max: number;
          starting_rir: number;
          sets_per_muscle_per_week: number;
          weeks_between_deloads: number;
          cardio_sessions_per_week: number;
          age: number | null;
          activity_level: ActivityLevel | null;
          meals_per_day: MealsPerDay | null;
          eating_approach: EatingApproach | null;
          emphasis_areas: string[];
          average_daily_steps: number | null;
          progress_tracking_methods: string[];
          fat_target: number | null;
          carb_target: number | null;
          bmr: number | null;
          tdee: number | null;
          secondary_rep_min: number;
          secondary_rep_max: number;
          isolation_rep_min: number;
          isolation_rep_max: number;
          compound_sets: number;
          accessory_sets: number;
          isolation_sets: number;
          rest_compound: number;
          rest_secondary: number;
          rest_isolation: number;
          last_seen_version: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          display_name?: string | null;
          height_inches?: number | null;
          current_weight?: number | null;
          target_weight?: number | null;
          protein_target_min?: number;
          protein_target_max?: number;
          calorie_target?: number;
          equipment_available?: string[];
          training_mode?: TrainingMode;
          sex?: string | null;
          experience_level?: ExperienceLevel | null;
          primary_goal?: PrimaryGoal | null;
          training_days_per_week?: number | null;
          preferred_days?: string[] | null;
          session_duration?: SessionDuration | null;
          training_location?: TrainingLocation | null;
          injuries?: string[] | null;
          avoided_exercises?: string[] | null;
          tracks_macros?: boolean;
          takes_creatine?: boolean;
          detrained_duration?: string | null;
          previous_training_style?: string | null;
          show_tooltips?: boolean;
          show_form_explanations?: FormExplanationLevel;
          split_type?: SplitType;
          onboarding_completed?: boolean;
          onboarding_completed_at?: string | null;
          compound_rep_min?: number;
          compound_rep_max?: number;
          starting_rir?: number;
          sets_per_muscle_per_week?: number;
          weeks_between_deloads?: number;
          cardio_sessions_per_week?: number;
          age?: number | null;
          activity_level?: ActivityLevel | null;
          meals_per_day?: MealsPerDay | null;
          eating_approach?: EatingApproach | null;
          emphasis_areas?: string[];
          average_daily_steps?: number | null;
          progress_tracking_methods?: string[];
          fat_target?: number | null;
          carb_target?: number | null;
          bmr?: number | null;
          tdee?: number | null;
          secondary_rep_min?: number;
          secondary_rep_max?: number;
          isolation_rep_min?: number;
          isolation_rep_max?: number;
          compound_sets?: number;
          accessory_sets?: number;
          isolation_sets?: number;
          rest_compound?: number;
          rest_secondary?: number;
          rest_isolation?: number;
          last_seen_version?: string;
        };
        Update: {
          id?: string;
          display_name?: string | null;
          height_inches?: number | null;
          current_weight?: number | null;
          target_weight?: number | null;
          protein_target_min?: number;
          protein_target_max?: number;
          calorie_target?: number;
          equipment_available?: string[];
          training_mode?: TrainingMode;
          sex?: string | null;
          experience_level?: ExperienceLevel | null;
          primary_goal?: PrimaryGoal | null;
          training_days_per_week?: number | null;
          preferred_days?: string[] | null;
          session_duration?: SessionDuration | null;
          training_location?: TrainingLocation | null;
          injuries?: string[] | null;
          avoided_exercises?: string[] | null;
          tracks_macros?: boolean;
          takes_creatine?: boolean;
          detrained_duration?: string | null;
          previous_training_style?: string | null;
          show_tooltips?: boolean;
          show_form_explanations?: FormExplanationLevel;
          split_type?: SplitType;
          onboarding_completed?: boolean;
          onboarding_completed_at?: string | null;
          compound_rep_min?: number;
          compound_rep_max?: number;
          starting_rir?: number;
          sets_per_muscle_per_week?: number;
          weeks_between_deloads?: number;
          cardio_sessions_per_week?: number;
          age?: number | null;
          activity_level?: ActivityLevel | null;
          meals_per_day?: MealsPerDay | null;
          eating_approach?: EatingApproach | null;
          emphasis_areas?: string[];
          average_daily_steps?: number | null;
          progress_tracking_methods?: string[];
          fat_target?: number | null;
          carb_target?: number | null;
          bmr?: number | null;
          tdee?: number | null;
          secondary_rep_min?: number;
          secondary_rep_max?: number;
          isolation_rep_min?: number;
          isolation_rep_max?: number;
          compound_sets?: number;
          accessory_sets?: number;
          isolation_sets?: number;
          rest_compound?: number;
          rest_secondary?: number;
          rest_isolation?: number;
          last_seen_version?: string;
        };
        Relationships: [];
      };
      exercises: {
        Row: {
          id: string;
          name: string;
          movement_pool: string;
          equipment_tags: string[];
          is_compound: boolean;
          default_sets: number | null;
          default_rep_min: number | null;
          default_rep_max: number | null;
          default_rest_seconds: number | null;
          default_rir: number | null;
          smith_equivalent_id: string | null;
          body_part: string | null;
          category: ExerciseCategory | null;
          instructions: string[] | null;
          primary_muscles: string[] | null;
          secondary_muscles: string[] | null;
          image_urls: string[] | null;
          gif_url: string | null;
          external_id: string | null;
          source: ExerciseSource | null;
          force_type: string | null;
          mechanic: string | null;
          difficulty: string | null;
          description: string | null;
          video_url: string | null;
          contraindicated_for: string[] | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          movement_pool: string;
          equipment_tags?: string[];
          is_compound?: boolean;
          default_sets?: number | null;
          default_rep_min?: number | null;
          default_rep_max?: number | null;
          default_rest_seconds?: number | null;
          default_rir?: number | null;
          smith_equivalent_id?: string | null;
          body_part?: string | null;
          category?: ExerciseCategory | null;
          instructions?: string[] | null;
          primary_muscles?: string[] | null;
          secondary_muscles?: string[] | null;
          image_urls?: string[] | null;
          gif_url?: string | null;
          external_id?: string | null;
          source?: ExerciseSource | null;
          force_type?: string | null;
          mechanic?: string | null;
          difficulty?: string | null;
          description?: string | null;
          video_url?: string | null;
          contraindicated_for?: string[] | null;
        };
        Update: {
          id?: string;
          name?: string;
          movement_pool?: string;
          equipment_tags?: string[];
          is_compound?: boolean;
          default_sets?: number | null;
          default_rep_min?: number | null;
          default_rep_max?: number | null;
          default_rest_seconds?: number | null;
          default_rir?: number | null;
          smith_equivalent_id?: string | null;
          body_part?: string | null;
          category?: ExerciseCategory | null;
          instructions?: string[] | null;
          primary_muscles?: string[] | null;
          secondary_muscles?: string[] | null;
          image_urls?: string[] | null;
          gif_url?: string | null;
          external_id?: string | null;
          source?: ExerciseSource | null;
          force_type?: string | null;
          mechanic?: string | null;
          difficulty?: string | null;
          description?: string | null;
          video_url?: string | null;
          contraindicated_for?: string[] | null;
        };
        Relationships: [];
      };
      user_exercise_prefs: {
        Row: {
          id: string;
          user_id: string;
          exercise_id: string;
          is_favorite: boolean;
          is_hidden: boolean;
          notes: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          exercise_id: string;
          is_favorite?: boolean;
          is_hidden?: boolean;
          notes?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          exercise_id?: string;
          is_favorite?: boolean;
          is_hidden?: boolean;
          notes?: string | null;
        };
        Relationships: [];
      };
      training_blocks: {
        Row: {
          id: string;
          user_id: string;
          block_number: number;
          start_date: string;
          is_active: boolean;
          rotation_notes: Json | null;
          total_weeks: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          block_number: number;
          start_date: string;
          is_active?: boolean;
          rotation_notes?: Json | null;
          total_weeks?: number;
        };
        Update: {
          id?: string;
          user_id?: string;
          block_number?: number;
          start_date?: string;
          is_active?: boolean;
          rotation_notes?: Json | null;
          total_weeks?: number;
        };
        Relationships: [];
      };
      block_exercises: {
        Row: {
          id: string;
          block_id: string;
          day_template: DayTemplate;
          slot_order: number;
          movement_pool: string;
          exercise_id: string;
          sets: number;
          rep_min: number;
          rep_max: number;
          rest_seconds: number;
          rir_target: number;
          is_anchor: boolean;
          variant_pool: Json | null;
          current_variant: string | null;
        };
        Insert: {
          id?: string;
          block_id: string;
          day_template: DayTemplate;
          slot_order: number;
          movement_pool: string;
          exercise_id: string;
          sets: number;
          rep_min: number;
          rep_max: number;
          rest_seconds: number;
          rir_target: number;
          is_anchor?: boolean;
          variant_pool?: Json | null;
          current_variant?: string | null;
        };
        Update: {
          id?: string;
          block_id?: string;
          day_template?: DayTemplate;
          slot_order?: number;
          movement_pool?: string;
          exercise_id?: string;
          sets?: number;
          rep_min?: number;
          rep_max?: number;
          rest_seconds?: number;
          rir_target?: number;
          is_anchor?: boolean;
          variant_pool?: Json | null;
          current_variant?: string | null;
        };
        Relationships: [];
      };
      workout_sessions: {
        Row: {
          id: string;
          user_id: string;
          block_id: string | null;
          day_template: string;
          week_number: number;
          scheduled_date: string;
          completed_at: string | null;
          recovery_rating: RecoveryRating | null;
          notes: string | null;
          is_deload: boolean;
          training_mode: TrainingMode | null;
          pre_mood: PreMood | null;
          energy_level: number | null;
          time_available_minutes: number | null;
          mood_adjusted: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          block_id?: string | null;
          day_template: string;
          week_number: number;
          scheduled_date: string;
          completed_at?: string | null;
          recovery_rating?: RecoveryRating | null;
          notes?: string | null;
          is_deload?: boolean;
          training_mode?: TrainingMode | null;
          pre_mood?: PreMood | null;
          energy_level?: number | null;
          time_available_minutes?: number | null;
          mood_adjusted?: boolean;
        };
        Update: {
          id?: string;
          user_id?: string;
          block_id?: string | null;
          day_template?: string;
          week_number?: number;
          scheduled_date?: string;
          completed_at?: string | null;
          recovery_rating?: RecoveryRating | null;
          notes?: string | null;
          is_deload?: boolean;
          training_mode?: TrainingMode | null;
          pre_mood?: PreMood | null;
          energy_level?: number | null;
          time_available_minutes?: number | null;
          mood_adjusted?: boolean;
        };
        Relationships: [];
      };
      set_logs: {
        Row: {
          id: string;
          session_id: string;
          user_id: string;
          exercise_id: string;
          set_number: number;
          weight: number | null;
          reps: number | null;
          rir: number | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          session_id: string;
          user_id: string;
          exercise_id: string;
          set_number: number;
          weight?: number | null;
          reps?: number | null;
          rir?: number | null;
          notes?: string | null;
        };
        Update: {
          id?: string;
          session_id?: string;
          user_id?: string;
          exercise_id?: string;
          set_number?: number;
          weight?: number | null;
          reps?: number | null;
          rir?: number | null;
          notes?: string | null;
        };
        Relationships: [];
      };
      food_cache: {
        Row: {
          id: string;
          source: string;
          external_id: string | null;
          food_name: string;
          serving_size: string | null;
          calories: number | null;
          protein: number | null;
          carbs: number | null;
          fat: number | null;
          raw_response: Json | null;
          search_terms: string[] | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          source: string;
          external_id?: string | null;
          food_name: string;
          serving_size?: string | null;
          calories?: number | null;
          protein?: number | null;
          carbs?: number | null;
          fat?: number | null;
          raw_response?: Json | null;
          search_terms?: string[] | null;
        };
        Update: {
          id?: string;
          source?: string;
          external_id?: string | null;
          food_name?: string;
          serving_size?: string | null;
          calories?: number | null;
          protein?: number | null;
          carbs?: number | null;
          fat?: number | null;
          raw_response?: Json | null;
          search_terms?: string[] | null;
        };
        Relationships: [];
      };
      nutrition_entries: {
        Row: {
          id: string;
          user_id: string;
          log_date: string;
          meal_type: MealType;
          food_name: string;
          serving_size: string | null;
          calories: number;
          protein: number;
          carbs: number;
          fat: number;
          food_cache_id: string | null;
          source: FoodSource | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          log_date?: string;
          meal_type: MealType;
          food_name: string;
          serving_size?: string | null;
          calories?: number;
          protein?: number;
          carbs?: number;
          fat?: number;
          food_cache_id?: string | null;
          source?: FoodSource | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          log_date?: string;
          meal_type?: MealType;
          food_name?: string;
          serving_size?: string | null;
          calories?: number;
          protein?: number;
          carbs?: number;
          fat?: number;
          food_cache_id?: string | null;
          source?: FoodSource | null;
        };
        Relationships: [];
      };
      user_food_favorites: {
        Row: {
          id: string;
          user_id: string;
          food_cache_id: string | null;
          custom_food_name: string | null;
          custom_calories: number | null;
          custom_protein: number | null;
          custom_carbs: number | null;
          custom_fat: number | null;
          custom_serving_size: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          food_cache_id?: string | null;
          custom_food_name?: string | null;
          custom_calories?: number | null;
          custom_protein?: number | null;
          custom_carbs?: number | null;
          custom_fat?: number | null;
          custom_serving_size?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          food_cache_id?: string | null;
          custom_food_name?: string | null;
          custom_calories?: number | null;
          custom_protein?: number | null;
          custom_carbs?: number | null;
          custom_fat?: number | null;
          custom_serving_size?: string | null;
        };
        Relationships: [];
      };
      bodyweight_log: {
        Row: {
          id: string;
          user_id: string;
          log_date: string;
          weight: number;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          log_date?: string;
          weight: number;
          notes?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          log_date?: string;
          weight?: number;
          notes?: string | null;
        };
        Relationships: [];
      };
      cardio_sessions: {
        Row: {
          id: string;
          user_id: string;
          session_date: string;
          cardio_type: CardioType;
          duration_minutes: number;
          distance: number | null;
          distance_unit: DistanceUnit;
          calories_burned: number | null;
          avg_heart_rate: number | null;
          intensity: CardioIntensity | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          session_date?: string;
          cardio_type: CardioType;
          duration_minutes: number;
          distance?: number | null;
          distance_unit?: DistanceUnit;
          calories_burned?: number | null;
          avg_heart_rate?: number | null;
          intensity?: CardioIntensity | null;
          notes?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          session_date?: string;
          cardio_type?: CardioType;
          duration_minutes?: number;
          distance?: number | null;
          distance_unit?: DistanceUnit;
          calories_burned?: number | null;
          avg_heart_rate?: number | null;
          intensity?: CardioIntensity | null;
          notes?: string | null;
        };
        Relationships: [];
      };
      exercise_insights: {
        Row: {
          id: string;
          exercise_id: string;
          tip_text: string;
          tip_category: TipCategory;
          source_citation: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          exercise_id: string;
          tip_text: string;
          tip_category: TipCategory;
          source_citation?: string | null;
        };
        Update: {
          id?: string;
          exercise_id?: string;
          tip_text?: string;
          tip_category?: TipCategory;
          source_citation?: string | null;
        };
        Relationships: [];
      };
      concept_tooltips: {
        Row: {
          id: string;
          term: string;
          definition: string;
          source_citation: string | null;
          category: TooltipCategory | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          term: string;
          definition: string;
          source_citation?: string | null;
          category?: TooltipCategory | null;
        };
        Update: {
          id?: string;
          term?: string;
          definition?: string;
          source_citation?: string | null;
          category?: TooltipCategory | null;
        };
        Relationships: [];
      };
      exercise_library_cache: {
        Row: {
          id: string;
          external_id: string;
          source: string;
          data: Json;
          fetched_at: string;
        };
        Insert: {
          id?: string;
          external_id: string;
          source: string;
          data: Json;
          fetched_at?: string;
        };
        Update: {
          id?: string;
          external_id?: string;
          source?: string;
          data?: Json;
          fetched_at?: string;
        };
        Relationships: [];
      };
      exercise_video_feedback: {
        Row: {
          id: string;
          user_id: string;
          exercise_id: string;
          video_url: string;
          video_title: string | null;
          platform: 'youtube' | 'tiktok' | 'instagram';
          liked: boolean;
          search_index: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          exercise_id: string;
          video_url: string;
          video_title?: string | null;
          platform?: 'youtube' | 'tiktok' | 'instagram';
          liked: boolean;
          search_index?: number;
        };
        Update: {
          id?: string;
          liked?: boolean;
          video_url?: string;
          video_title?: string | null;
          search_index?: number;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}

// Convenience aliases
export type UserProfile = Database['public']['Tables']['user_profiles']['Row'];
export type Exercise = Database['public']['Tables']['exercises']['Row'];
export type TrainingBlock = Database['public']['Tables']['training_blocks']['Row'];
export type BlockExercise = Database['public']['Tables']['block_exercises']['Row'];
export type WorkoutSession = Database['public']['Tables']['workout_sessions']['Row'];
export type SetLog = Database['public']['Tables']['set_logs']['Row'];
export type NutritionEntry = Database['public']['Tables']['nutrition_entries']['Row'];
export type FoodCache = Database['public']['Tables']['food_cache']['Row'];
export type BodyweightLog = Database['public']['Tables']['bodyweight_log']['Row'];
export type CardioSession = Database['public']['Tables']['cardio_sessions']['Row'];
export type ExerciseInsight = Database['public']['Tables']['exercise_insights']['Row'];
export type ConceptTooltip = Database['public']['Tables']['concept_tooltips']['Row'];
export type ExerciseLibraryCache = Database['public']['Tables']['exercise_library_cache']['Row'];
export type ExerciseVideoFeedback = Database['public']['Tables']['exercise_video_feedback']['Row'];
